import type { Metadata } from "next";
import AppLayout from "@/components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
